### ISSUE TITLE
[custom-feedback] Fixes to the Dockerfile and project structure before open sourcing

### ISSUE THREAD

**Issue by lfzawacki** [bigbluebutton/custom-feedback#5]
* [x] has no license
* [x] frontend has dev dependencies (e.g. jest)
* [x] server logger has some SFU and transcription controller stuff
* [x] Winston is bad in these newer versions, think about switching to Pino or something similar later
* [x] Docker has Node 18 (prefer to use LTS/20 or you can even use Node 22 at once)
* [x] use Node alpine in docker, there is no need to use the full image
* [ ] it is interesting to include automations from Trivy and Dockerhub (copy from here https://github.com/mconf/bbb-webhooks/tree/develop/.github/workflows)

**Comment by AtilaU19** [comment]
The following commit fixes most of the issues:
https://github.com/mconf/custom-feedback/commit/8e7f80c727bfa19e23c91bbb55f65e9a9df60520
You just need:
 - includes Trivy and Dockerhub automations.
 - decide and issue the license
